apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodeforicptest-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeforicptest-app
    spec:
      containers:
      - name: nodeforicptest
        image: frck/nodeforicptest
        imagePullPolicy: Always
        ports:
        - containerPort: 6002
# vim: set ts=2 expandtab!:
